#!/bin/bash

echo "======================================"
echo "  TEST DE CONNEXION AfrikaPharma"
echo "======================================"
echo ""
echo "✅ Serveur en cours d'exécution"
echo "   URL: http://localhost:3001"
echo ""
echo "📍 Accédez à l'une de ces URLs:"
echo ""
echo "   1️⃣  PAGE DE CONNEXION"
echo "       URL: http://localhost:3001/login"
echo ""
echo "   2️⃣  IDENTIFIANTS DE CONNEXION"
echo "       Utilisateur: admin"
echo "       Mot de passe: Admin123!"
echo ""
echo "   3️⃣  APRÈS CONNEXION RÉUSSIE"
echo "       Vous serez redirigé vers: /dashboard"
echo ""
echo "======================================"
echo "  ALTERNATIVE: Utiliser AfrikaPharma"
echo "======================================"
echo ""
echo "Si vous voulez utiliser l'application AfrikaPharma avec:"
echo "- /login-admin"
echo "- /login-seller"
echo ""
echo "Exécutez ces commandes:"
echo "  cd AfrikaPharma"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "Puis accédez à:"
echo "  http://localhost:3000/login-admin"
echo ""
echo "======================================"
