name: Build Android APK (debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies (with retries)
        run: |
          set -euo pipefail
          retries=3
          until npm ci --no-audit --no-fund; do
            retries=$((retries-1))
            echo "npm ci failed, retries left: $retries"
            if [ "$retries" -le 0 ]; then
              echo "npm ci failed after retries"; exit 1
            fi
            sleep 5
          done

      - name: Build Next (production)
        run: npm run build

      - name: Setup CAPACITOR_SERVER_URL
        run: echo "CAPACITOR_SERVER_URL=https://afrikapharma-delta.vercel.app" >> $GITHUB_ENV

      - name: Sync Capacitor Android (with retries)
        run: |
          set -euo pipefail
          retries=3
          until npx cap sync android; do
            retries=$((retries-1))
            echo "npx cap sync failed, retries left: $retries"
            if [ "$retries" -le 0 ]; then
              echo "npx cap sync failed after retries"; exit 1
            fi
            sleep 5
          done

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: r0adkll/setup-android@v2
        with:
          api-levels: '33'
          build-tools: '33.0.2'
          components: 'platform-tools'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build APK (Gradle)
        working-directory: android
        run: |
          set -euo pipefail
          retries=2
          until ./gradlew assembleDebug --no-daemon --stacktrace; do
            retries=$((retries-1))
            echo "Gradle build failed, retries left: $retries"
            if [ "$retries" -le 0 ]; then
              echo "Gradle build failed after retries"; exit 1
            fi
            sleep 10
          done

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
